export default [{
        "name": "电商/团购",
        "value": "0010"
    },
    {
        "name": "线下零售",
        "value": "0020"
    }, {
        "name": "生活/家居",
        "value": "0030"
    }, {
        "name": "餐饮/食品",
        "value": "0040"
    }, {
        "name": "生活/咨询服务",
        "value": "0050"
    }, {
        "name": "票务/旅游",
        "value": "0060"
    }, {
        "name": "网络虚拟服务",
        "value": "0070"
    }, {
        "name": "教育/培训",
        "value": "0080"
    }, {
        "name": "娱乐/健身服务",
        "value": "0090"
    }, {
        "name": "房地产",
        "value": "0100"
    }, {
        "name": "医疗",
        "value": "0110"
    }, {
        "name": "收藏/拍卖",
        "value": "0120"
    }, {
        "name": "苗木/花卉",
        "value": "0130"
    }, {
        "name": "交通运输服务",
        "value": "0140"
    }, {
        "name": "生活缴费类",
        "value": "0150"
    }, {
        "name": "公益",
        "value": "0160"
    }, {
        "name": "通信",
        "value": "0170"
    }, {
        "name": "金融",
        "value": "0180"
    }, {
        "name": "其他",
        "value": "0190"
    }
]